apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance 
  namespace: openshift-logging
spec:
  outputs:
    - name: external-es
      type: elasticsearch
      version: 7
      url: https://external.elasticsearch.com:9200
      secret:
        name: external-es-secret
  inputs:
    - name: my-app-logs
      application:
        namespaces:
          - my-project
  pipelines: {}
    - name: audit-infra-my-app-logs
      inputRefs:
        - audit
        - infrastructure
        - my-app-logs
      outputRefs:
        - external-es

