---
# Create ns
---
apiVersion: v1 
kind: Namespace 
metadata:
  name: metallb-system
---
# Create operatorgroup
---
apiVersion: operators.coreos.com/v1 
kind: OperatorGroup 
metadata:
  name: metallb-operator
  namespace: metallb-system
---
# Create subscription
---
apiVersion: operators.coreos.com/v1alpha1 
kind: Subscription 
metadata:   
  name: metallb-operator-sub
  namespace: metallb-system 
spec:
  channel: stable
  name: metallb-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
# Label ns (optional)
---
apiVersion: v1 
kind: Namespace 
metadata:   
  name: metallb-system
  labels:
    openshift.io/cluster-monitoring: 'true'
---
# Create MetalLB instance
---
apiVersion: metallb.io/v1beta1 
kind: MetalLB 
metadata:   
  name: metallb
  namespace: metallb-system
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ""
---
# Create IPAddressPool
---
apiVersion: metallb.io/v1beta1 
kind: IPAddressPool 
metadata:   
  namespace: metallb-system   
  name: ipa-pool-1
spec:
  addresses:
    - 192.168.132.0/24
  serviceAllocation:
    namespaces:
      - external-ip
---
# Create L2Advertisement
---
apiVersion: metallb.io/v1beta1 
kind: L2Advertisement 
metadata:
  name: l2advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
    - ipa-pool-1
  interfaces:
    - br-ex
    - br-int
