apiVersion: v1 
kind: Service 
metadata:
  name: metallb-httpd-1
  namespace: external-ip
  labels:
    app: httpd-example
  annotations:
    metallb.universe.tf/address-pool: ipa-pool-1
spec:
  type: LoadBalancer
  selector:     
    name: httpd-example
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP   
  loadBalancerIP: 192.168.132.252
