---
#apiVersion: v1
#kind: Secret  
#metadata:
#  name: elasticsearch-credentials
#  namespace: openshift-logging 
#data:
#  username: Zmx1ZW50ZA==
#  password: c2VjcmV0bwo=
#type: Opaque
---
apiVersion: "logging.openshift.io/v1" 
kind: ClusterLogForwarder 
metadata:
  name: instance
spec:
  outputs:
    - elasticsearch:
        version: 7
      name: remote-elasticsearch
      secret:
        name: elasticsearch-credentials
      type: elasticsearch
      url: 'https://10.0.144.26:9200'
  pipelines:
    - inputRefs:
        - infrastructure    
        - application
      name: forward-to-remote
      outputRefs:
        - remote-elasticsearch
