- name: Install ODF Operator in OpenShift
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Ensure openshift-storage namespace exists
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: openshift-operators

    - name: Create OperatorGroup 
      kubernetes.core.k8s:
        state: present
        namespace: openshift-operators
        definition:
          apiVersion: operators.coreos.com/v1
          kind: OperatorGroup
          metadata:
            name: global-operators
            namespace: openshift-operators
          spec:
            targetNamespaces:
              - openshift-operators

    - name: Create Subscription for ODF Operator
      kubernetes.core.k8s:
        state: present
        namespace: openshift-storage
        definition:
          apiVersion: operators.coreos.com/v1alpha1
          kind: Subscription
          metadata:
            name: odf-operator
            namespace: openshift-storage
          spec:
            channel: "stable-4.17"
            name: "odf-operator"
            source: "redhat-operators"
            sourceNamespace: "openshift-marketplace"
            startingCSV: odf-operator.v4.17.5-rhodf

