apiVersion: v1
kind: Service
metadata:
  annotations:
    description: Exposes and load balances the application pods
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: "2024-03-06T13:08:48Z"
  labels:
    app: httpd-example
    template: httpd-example
  name: httpd-example
  namespace: external-ip
  resourceVersion: "266724"
  uid: db8ff62a-32f1-4eb6-8ee7-c615a373241d
spec:
  clusterIP: 172.30.241.3
  clusterIPs:
  - 172.30.241.3
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    name: httpd-example
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
