apiVersion: v1
kind: Service
metadata:
  name: flask-metrics
  namespace: metrics-ws
spec:
  selector:
    app: flask-metrics
  ports:
    - name: web
      port: 8080
      targetPort: 8080
    - name: metrics
      port: 8000
      targetPort: metrics
